BE_guestBook/BE_guestBook/BE_guestBook/urls.py
from django.contrib import admin
from django.urls import path, include
from guest_app import views
from guest_app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('guestapp/', include('guest_app.urls')),
]

BE_guestBook/BE_guestBook/guest_app/urls.py
from django.urls import path
from guest_app import views

app_name = 'guest_app'

urlpatterns = [
    path('', views.GuestList.as_view(), name='guestbook_list'),
]

BE_guestBook/BE_guestBook/guest_app/models.py
from django.db import models

# Create your models here.


class GuestBook(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=10)
    content = models.TextField(null=True)
    datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    

BE_guestBook/BE_guestBook/guest_app/views.py
from django.shortcuts import render
from .models import GuestBook
from django.views.generic import ListView

# Create your views here.


def index(request):
    books = GuestBook.objects.all()
    return render(request, "index.html", {'books': books})

class GuestList(ListView):
    model=GuestBook
    ordering=['-datetime']
    
def index(request):
    return render(request, "guest_app/index.html")

BE_guestBook/BE_guestBook/guest_app/templates/guest_app/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>방명록</title>
</head> 
<body>
    <div> {% block index %} {% endblock %}</div>
    {% include 'guest_app/footer.html' %}
</body>
</html>

BE_guestBook/BE_guestBook/guest_app/templates/guest_app/footer.html
<div style="border: 2px solid purple; margin-top: 50px">
    <h5>이것은 요영이가 만든 미니홈피입니다.</h5>
</div>

BE_guestBook/BE_guestBook/guest_app/templates/guest_app/guestbook_list.html
{% extends 'guest_app/base.html' %}
{% block index %}
<h1>방명록 목록</h1>
<ul>
  {% for book in guestbook_list %}
  <li>{{book.title}}-{{book.author}} ({{book.datetime}})</li>
  {% empty %}
  <li>방명록이 없습니다</li>
  {%endfor%}
</ul>
{% endblock %}

BE_guestBook/BE_guestBook/guest_app/templates/guest_app/index.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Guestbook</title>
  </head>
  <body>
    <h1>환영합니다!</h1>
    <h2>여기는 아름다운 미니홈피</h2>
    <a href="{% url 'guest_app:guestbook_list' %}">방명록 바로가기</a>
    {% include 'guest_app/footer.html' %}
  </body>
</html>

BE_guestBook/BE_guestBook/guest_app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Guestbook</title>
  </head>
  <body>
    <h1>방명록 목록</h1>
    <ul>
      {% for book in books %}
      <li>{{book.title}}-{{book.author}} ({{book.datetime}})</li>
      {%endfor%}
    </ul>
  </body>
</html>