BE_CRUD/BE_CRUD/BE_CRUD/urls.py
from django.contrib import admin
from django.urls import path, include
from crudApp import views
from crudApp.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crudApp.urls')),
]

BE_CRUD/BE_CRUD/crudApp/urls.py
from django.urls import path
from crudApp import views
from crudApp.views import *

app_name = 'crudApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
]

BE_CRUD/BE_CRUD/crudApp/models.py
from django.db import models

# Create your models here.

class Index(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(blank=True)
    date = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.title

BE_CRUD/BE_CRUD/crudApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *

def index(request):
    todo = Index.objects.all()
    return render(request, 'index.html', {'todo':todo})

def create(request):
    if request.method == "POST":
        index=Index()
        index.title=request.POST.get("title")
        index.content=request.POST.get("content")
        index.save()
        return redirect("crudApp:index")
    return render(request, "create.html")

def detail(request, id):
    todo= get_object_or_404(Index, pk=id)
    return render(request,'detail.html', {"todo": todo})

def update(request, id):
    update_todo=get_object_or_404(Index, pk=id)
    if request.method == 'POST':
        update_todo.title = request.POST.get('title')
        update_todo.content=request.POST.get("content")
        update_todo.date=request.POST.get("date")
        update_todo.save()
        return redirect("curdApp:detail", update_todo.pk)
    return render(request, 'update.html', {'update_todo':update_todo})

def delete(request, id):
    delete_todo=get_object_or_404(Index, pk=id)
    delete_todo.delete()
    return redirect('curdApp:index')

BE_CRUD/BE_CRUD/crudApp/templates/create.html
<form action="{%url 'crudApp:create' %}" method="POST">
    {% csrf_token %}
    <label for="title">제목</label>
    <input type="text" name="title" /><br/><br/>
    <label for="content">본문</label>
    <textarea name="content" id="" cols="30" rows="10"></textarea><br/>
    <input type="submit" value=제출 />
</form>

BE_CRUD/BE_CRUD/crudApp/templates/detail.html
<body>
    <p>게시물 번호: {{todo.pk}}</p>
    <h3>제목:{{todo.title}}</h3></a>
    <p>내용:{{todo.content}}</p>
    <p>생성 시간:{{todo.date}}</p>
    <a href = '{% url 'crudApp:update' todo.pk %}'><button>수정하기</button></a>
    <a href = '{% url 'crudApp:index' %}'><button>홈으로</button></a>
    <a href = '{% url 'crudApp:delete' todo.pk %}'><button>삭제하기</button></a>
    <br><br><br>
</body>

BE_CRUD/BE_CRUD/crudApp/templates/index.html
<h1>함요영의 TodoList</h1>
<a href = "{% url 'crudApp:create' %}"><button>새 글 등록</button></a>
<hr>
<body>
    {%for obj in todo%}
    <p>게시물 번호: {{obj.pk}}</p>
    <a href="{% url 'crudApp:detail' obj.pk %}"><h3>제목:{{obj.title}}</h3></a>
    <br><br><br>
    {%endfor%}
</body>

BE_CRUD/BE_CRUD/crudApp/templates/update.html
<form action="{% url 'crudApp:update' update_todo.pk%}" method="POST">
    {% csrf_token %}
    <h3>수정하기</h3>
    <label for='tilte'>제목</label>
    <input type='text' name='title' value="{{todo.title}}" /><br/><br/>
    <label for = 'content'>본문</label>
    <textarea name='content' id="" cols="30" rows="10">{{todo.content}}</textarea>
    <input type='submit' value='제출'>
</form>