BE_TEST/BE_TEST/BE_TEST/urls.py
from django.contrib import admin
from django.urls import path, include
from testApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('testApp.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

BE_TEST/BE_TEST/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

BE_TEST/BE_TEST/testApp/urls.py
from django.urls import path
from testApp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('detail/<int:id>/', views.detail, name='detail'),
]

BE_TEST/BE_TEST/accounts/models.py
from django.db import models

# Create your models here.

BE_TEST/BE_TEST/testApp/models.py
from django.db import models

# Create your models here.

class Basic(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField(null=True)
    date = models.DateField(auto_now_add=True)
    
    def __self__(self):
        return self.title

BE_TEST/BE_TEST/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager as DjangoUserManager

class UserManager(DjangoUserManager):
    def _create_user(self, username, email, password, **extra_fields):
        if not email:
            raise ValueError('이메일은 필수 값입니다.')
        
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
        
    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)
        
    def create_superuser(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(username, email, password, **extra_fields)
    
class User(AbstractUser):
    phone = models.CharField(verbose_name='전화번호', max_length=11)
    
    objects = UserManager()

BE_TEST/BE_TEST/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserBaseForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = '__all__'
        
class UserCreateForm(UserBaseForm):
    password2 = forms.CharField(widget=forms.PasswordInput())
    class Meta(UserBaseForm.Meta):
        fields = ['username', 'email', 'phone', 'password']
        
class SignUpForm(UserCreateForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ['username', 'email']

BE_TEST/BE_TEST/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import UserCreateForm, SignUpForm

def signup_view(request):
    if request.method == 'GET': # GET 요청 시 HTML 응답
        form = SignUpForm
        context = {'form':form}
        return render(request, 'accounts/signup.html', context)
    else:
        # POST 요청 시 데이터 확인 후 회원 생성
        form = SignUpForm(request.POST)
        
        if form.is_valid():
            #회원가입 처리
            instance = form.save()
            return redirect('index')
        else:
            #리다이렉트
            return redirect('accounts:signup')
        
def login_view(request):
    if request.method == 'GET':
        #로그인 HTML 응답
        return render(request, 'accounts/login.html', {'form':AuthenticationForm()})
    else:
        # 데이터 유효성 검사
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            # 비즈니스 로직 처리 (회원가입 처리) - 로그인 처리
            login(request, form.user_cache)
        
            return redirect('index')
        else:
            # 비즈니스 로직 처리 (회원가입 처리) - 로그인 실패
            # 응답
            return render(request, 'accounts/login.html', {'form' : form})
        password = request.POST.get('password')
        
def logout_view(request):

    if request.user.is_authenticated:
        logout(request)
    return redirect('index')

BE_TEST/BE_TEST/testApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
# Create your views here.

def index(request):
    lists = Basic.objects.all()
    return render (request, 'index.html', {'lists':lists})

def create(request):
    if request.method == 'POST':
        basic=Basic()
        basic.title = request.POST.get('title')
        basic.date = request.POST.get('date')
        basic.content = request.POST.get('content')
        basic.save()
        return redirect('index')
    return render (request, 'create.html')

def detail(request, id):
    list_detail = get_object_or_404(Basic, pk=id)
    return render(request, 'detail.html', {'list_detail':list_detail})

BE_TEST/BE_TEST/users/views.py
from django.shortcuts import render

# Create your views here.

BE_TEST/BE_TEST/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>로그인</title>
</head>
<body>
    <h1>Login</h1>
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        <div>
            {{form.as_p}}
        </div>
        <div>
            <input type="submit"> 
        </div>
    </form>
</body>
</html>

BE_TEST/BE_TEST/accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원가입</title>
</head>
<body>
    <h1>회원가입</h1>
    <form action="" method='POST' enctype='multipart/form-data'>
        {% csrf_token %}
        <div>
            {{ form.as_p }}
        </div>
        <div>
            <input type='submit'>
        </div>
    </form>
</body>
</html>

BE_TEST/BE_TEST/testApp/templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>새 글 작성</h1>
    <form action="{% url 'create' %}" method="POST">
        {% csrf_token %}
        <label for='title'>제목</label>
        <input type='text' name='title'/><br><br>
        <label for ='content'>내용</label>
        <textarea name="content" id='content' cols="30" rows="10"></textarea><br><br>
        <input type="submit" value="제출">
    </form>
</body>
</html>

BE_TEST/BE_TEST/testApp/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <br><br>
    <h3>{{list_detail.title}}</h3><br>
    {{list_detail.content}}<br><br>
    {{list_detail.date}}<br><br>
    <a href = "{% url 'index' %}"><button>돌아가기</button></a>
</body>
</html>

BE_TEST/BE_TEST/testApp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>글 목록</h1>
    <br><br>
    {% for list in lists %}
    <h3><a href="{% url 'detail' list.pk %}">{{list.title}}</a></h3>
    {{list.date}}
    {% endfor %}
    <br><br>
    <a href = "{% url 'create' %}"><button>글 작성</button></a><br><br>
    {% if request.user.is_authenticated %}
    <span>
        로그인 상태: {{ request.user.username }}
    </span>
    {% else %}
    <span>
        비로그인 상태
    </span>
    {% endif %}
</body>
</html>